# Unstable features 
unstable_features = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
wrap_comments = true
group_imports = "StdExternalCrate"
comment_width = 100